server:
  address: 192.168.7.190

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hub
    username: root
    password: Awltjr!0419
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    s3:
      bucket: toongether-s3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: AKIA32L5MJWELTOGVDOA
      secret-key: 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